[black]
args = ["--check"]
help = "Code formatter for python."
fast = true
test = true

[black.format]
args = []

[flake8]
args = ["--max-line-length=88", "--ignore=E203"]
help = "Code style checker for python."
fast = true
test = true

[autoflake]
args = [
    "--in-place",
    "--recursive",
    "--expand-star-imports",
    "--remove-all-unused-imports"
]
help = "Remove unused imports and variables"
format = true
standard = false

# The isort problem
# =================
#
# Unfortunaly, "isort" is very effected by the environments it is running on.
#This is causing a lot of problems when running isort using tox or in a virtual machine
#during CI/CD process.
#
#This behavior should be fixed by version 5.0.0, but until than we can not use isort
#(even though we really want to...).
#
# Once this version is out, we will return using isort.
#
#[isort]
#args = [
#    "--recursive",
#    "--multi-line=3",
#    "--trailing-comma",
#    "--force-grid-wrap=0",
#    "--use-parentheses",
#    "--lines=88",
#    "--check-only"
#]
#help = "Tool for sorting and cleaning python imports."
#fast = true
#test = true
#
#[isort.format]
#args = [
#    "--recursive",
#    "--multi-line=3",
#    "--trailing-comma",
#    "--force-grid-wrap=0",
#    "--use-parentheses",
#    "--lines=88"
#]

[mypy]
args = ["--ignore-missing-imports"]
help = "Validate types using mypy."
fast = true
test = true

[pylint]
args = [
    "--ignore-imports=y",
    "--disable=C0203,C0330,E0401,C0411,E0611,E1130"
    ]
help = "Python code linter"

[pylint.test]
args = [
    "--ignore-imports=y",
    "--disable=C0103,C0114,C0115,C0116,C0203,C0204,C0330,C0411",
    "--disable=E1101,E1130,E0401,E0611,E1120,E1139",
    "--disable=R0801,R0902,R0903,R0904,R0913,W0201"]

[pydocstyle]
args = ["--ignore=D203,D212,D400,D401"]
help = "Tool for python docstring style enforcing"
test = false